package io.github.xstefanox.underkow.test

internal class AnException : Exception()
